# Money Craft: Insights

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
scv = pd.read_csv('moneycraft_customer_view.csv')

scv.head(10)

,customer_id,signup_month,last_active,close_month,reason_code,tenure_months,channel,region,age_band,promo,first_account_tier,last_account_tier,max_fee,total_revenue,churned
0,1,2022-01,2022-06,2022-07,Switched provider,6,Comparison Site,Scotland,25-34,False,Classic,Classic,0,0,True
1,2,2022-01,2024-12,NaN,NaN,36,Online,London,55-64,False,Silver,Platinum,28,595,False
2,3,2022-01,2024-12,NaN,NaN,36,Branch,South East,25-34,False,Platinum,Platinum,28,848,False
3,4,2022-01,2024-12,NaN,NaN,36,Referral,London,25-34,True,Silver,Silver,11,330,False
4,5,2022-01,2022-10,2022-11,Bereavement,10,Comparison Site,South East,35-44,False,Silver,Classic,11,33,True
5,6,2022-01,2024-12,NaN,NaN,36,Branch,South East,35-44,False,Gold,Gold,18,536,False
6,7,2022-01,2023-05,NaN,Unknown,17,Outbound,Scotland,45-54,False,Silver,Silver,11,187,True
7,8,2022-01,2024-12,NaN,NaN,36,Online,South East,45-54,False,Silver,Gold,18,508,False
8,9,2022-01,2024-12,NaN,NaN,36,Online,North,35-44,False,Silver,Platinum,28,563,False
9,10,2022-01,2024-12,NaN,NaN,36,Broker/IFA,Scotland,18-24,True,Gold,Platinum,28,840,False

In [2]:
spend = pd.read_csv('moneycraft_marketing_spend.csv')

spend.head(10)

     month          channel  spend_gbp
0  2022-01           Branch     7310.0
1  2022-01       Broker/IFA     4014.0
2  2022-01  Comparison Site     3162.0
3  2022-01           Online     3945.0
4  2022-01         Outbound     4899.0
5  2022-01         Referral     1872.0
6  2022-02           Branch     7882.0
7  2022-02       Broker/IFA     1989.0
8  2022-02  Comparison Site     3266.0
9  2022-02           Online     4231.0